### ISSUE TITLE
API Week Workshops

### ISSUE THREAD

**Issue by sohilpandya** [foundersandcoders/workshop-QMUL#2]
### Workshops

**Choose a Workshop from the list below and in the linked issue, add the content for the given workshop.**
- [ ] Monday GitHub Workshop #3 
- [ ] Monday HTML/CSS/JS Workshop #4
- [ ] Tuesday Postman Tutorial #9
- [ ] Tuesday NASA #5 / Stack Overflow #6
- [ ] Wednesday TFL Workshop #7
- [ ] Thursday Google Maps / Open Maps #8
- [ ] Any Extra Workshops?
- [ ] Friday Combination Project => Direct them to Chart JS if they would like to do Visualisation.

Hey @MyPitit @tormod17 @JackTierney! 

I have created these issues and also assigned some of them out, please have a look at them, all the resources for them should be linked back to the issue so that we can track everything that we are doing, and appropriate feedback will not be lost! 😄

**Comment by MyPitit** [comment]
Nice one @sohilpandya !

**Comment by MyPitit** [comment]
What about week two? I know is going to be like a big project but we will need to think about planning too :)

**Comment by tormod17** [comment]
Link to [FAC7 readme](https://github.com/FAC7/READMEs/blob/master/week3/API/whatisanapi.md) what's an API.

**Comment by MyPitit** [comment]
# Week one planning

## Monday

**10:00 - 11:00** Name Game +   Intro + course overview
**11:00  - 13:00** Github workshop + [Form workshop](https://github.com/katbow/FAC8day1) (@MyPitit) 
**13:00 - 14:00 Lunch**
**14:00 - 16:30** [Form workshop](https://github.com/katbow/FAC8day1)
**16:30 - 17:00** Review

## Tuesday - Nasa API, Stackoverflow or youtube (@JackTierney and @tormod17)

**10:00 - 10:45** Intro to API
**Topics:** 
- Restful
- Headers and body of request 
- JSONP and cors origin
- Status codes
- End points
- URL and URI
- HTTP Requests

**10:45 - 11:15** Postman or Curl
**11:15 - 13:00** Nasa API (@JackTierney)
**13:00 - 14:00 Lunch**
**14:00 - 16:30** Stackoverflow or youtube (@tormod17)
**16:30 - 17:00** Review

## Wednesday - TFL (@sohil Sohil)

**10:00 - 11:00** Morning Challenge (LINK)
**11:00 - 13:00** TFL Workshop
**13:00 - 14:00 Lunch**
**14:00 - 14:15** Quick Review
**14:15 - 14:30** Paired Project
**16:30 - 17:00** Project Presentations (3min per Pair)

## Thursday -  Google Maps APIs (@MyPitit)

**10:00 - 11:00** Morning Challenge (LINK)
**11:00 - 13:00** Google Maps APIs Workshop
**13:00 - 14:00 Lunch**
**14:00 - 14:30** Paired Project
**16:30 - 17:00** Project Presentations (3min per Pair)

## Friday

Friday Combination Project => Direct them to Chart JS if they would like to do Visualisation.

### More resources for _Intro to API_

[API slides](https://docs.google.com/presentation/d/1GjtRry0XMsaX9FkdEHyxge2KLbDutd7w_85JE1wZF4U/edit#slide=id.p).

**Comment by tormod17** [comment]
Hey guys I have made some additions to the API slides which will hopefully take them up to the stackover flow part. [Tormod's slides](https://docs.google.com/presentation/d/1ek5TqTSXNdYO1CFZ4GsNHs9QsdmyNnHhCtCc__-Dy8A/edit?usp=sharing)

**Comment by tormod17** [comment]
[public API's](https://github.com/toddmotto/public-apis)

**Comment by tormod17** [comment]
[Basics of javascript](http://autotelicum.github.io/Smooth-CoffeeScript/literate/js-intro.html)
